-- "JDBC/JDBC" 사용자 계정 추가

CREATE USER "C##JDBC" IDENTIFIED BY JDBC; 
-- 권한 설정
GRANT CONNECT, RESOURCE TO "C##JDBC";
-- 테이블스페이스 관련 설정
ALTER USER "C##JDBC" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;