create table MemberList (
    USERNO number PRIMARY KEY,
    USERID VARCHAR2(30) UNIQUE NOT NULL,
    USERPW VARCHAR2(30) NOT NULL,
    USERNAME VARCHAR2(20) NOT NULL,
    GENDER CHAR(2) CHECK(GENDER IN('M', 'F', 'm', 'f')),
    SSN VARCHAR2(30) UNIQUE NOT NULL,
    AGE NUMBER,
    HEIGHT NUMBER,
    WEIGHT NUMBER,
    ENROLLDATE DATE);


drop table memberlist cascade constraints;
CREATE SEQUENCE SEQ_MEM
NOCACHE;





select * from MemberList;

create table MemberSelection (
    USERNO NUMBER REFERENCES MEMBERLIST,
    BURGERKING VARCHAR2(300),
    HANSOT VARCHAR2(300),
    HOMECOOK VARCHAR2(300),
    TOTALKCAL NUMBER,
    TOTALPRICE NUMBER,
    INSERTDATE DATE NOT NULL,
    PRIMARY KEY(USERNO,INSERTDATE));