/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-02 09:19:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.member.model.vo.Member;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/workspace/5_JSP/jstlProject/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1711943105495L));
    _jspx_dependants.put("/views/member/../common/menubar.jsp", Long.valueOf(1712021233942L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>JSP Project</title>\r\n");
      out.write("<style>\r\n");
      out.write(".outer {\r\n");
      out.write("	background: black;\r\n");
      out.write("	color: white;\r\n");
      out.write("	width: 1000px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	margin-top: 50px;\r\n");
      out.write("}\r\n");
      out.write("/* margin: auto; => 왼쪽,오른쪽 동일한 비율로 가운데로 정렬 */\r\n");
      out.write("#enroll-form table {\r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#enroll-form input {\r\n");
      out.write("	margin: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("	padding-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");

String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>JSP Project</title>\r\n");
      out.write("<style>\r\n");
      out.write(".login-area>* {\r\n");
      out.write("	float: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-area a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-area {\r\n");
      out.write("	background: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu {\r\n");
      out.write("	display: table-cell; /* table의 cell 형식처럼 바꿔주는 속성. */\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	display: block;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	line-height: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu a:hover, .login-user a:hover {\r\n");
      out.write("	background: darkgrey;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"\r\n");
      out.write("	integrity=\"sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("</script>\r\n");
      out.write("<!-- bootstrap CSS -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<!-- bootstrap JS -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<h1 align=\"center\">Welcome Jaeyoon World</h1>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"login-area\">\r\n");
      out.write("		<!-- 1) 로그인 전-->\r\n");
      out.write("		");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      boolean _jspx_th_c_005fchoose_005f0_reused = false;
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("			");
            //  c:when
            org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
            boolean _jspx_th_c_005fwhen_005f0_reused = false;
            try {
              _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              // /views/member/../common/menubar.jsp(80,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
              if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("				<form action=\"");
                  out.print(contextPath);
                  out.write("/login.me\" method=\"POST\">\r\n");
                  out.write("					<table>\r\n");
                  out.write("						<tr>\r\n");
                  out.write("							<th>아이디</th>\r\n");
                  out.write("							<td><input type=\"text\" name=\"userId\" required /></td>\r\n");
                  out.write("						</tr>\r\n");
                  out.write("						<tr>\r\n");
                  out.write("							<th>비밀번호</th>\r\n");
                  out.write("							<td><input type=\"password\" name=\"userPwd\" required></td>\r\n");
                  out.write("						</tr>\r\n");
                  out.write("						<tr>\r\n");
                  out.write("							<th colspan=\"2\">\r\n");
                  out.write("								<button type=\"submit\">로그인</button>\r\n");
                  out.write("								<button type=\"button\" onclick=\"enrollPage()\">회원가입</button>\r\n");
                  out.write("							</th>\r\n");
                  out.write("						</tr>\r\n");
                  out.write("					</table>\r\n");
                  out.write("					<script>\r\n");
                  out.write("            	function enrollPage() {\r\n");
                  out.write("            		// 회원가입 페이지를 요청\r\n");
                  out.write("            		//  location.href = \"");
                  out.print(contextPath);
                  out.write("/views/member/memberEnrollForm.jsp\"; \r\n");
                  out.write("            		// 디렉토리 구조가 url에 그대로 노출 => 보안에 취약\r\n");
                  out.write("            		\r\n");
                  out.write("            		// 단순한 페이지 요청도 서블릿을 통해 처리될 수 있도록 하자.\r\n");
                  out.write("            		location.href = \"");
                  out.print(contextPath);
                  out.write("/enrollForm.me\";\r\n");
                  out.write("            	}\r\n");
                  out.write("            </script>\r\n");
                  out.write("				</form>\r\n");
                  out.write("			");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
              _jspx_th_c_005fwhen_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
            }
            out.write("\r\n");
            out.write("			");
            //  c:otherwise
            org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
            boolean _jspx_th_c_005fotherwise_005f0_reused = false;
            try {
              _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
              if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("				<!-- 2) 로그인 후-->\r\n");
                  out.write("				<div class=\"login-user\">\r\n");
                  out.write("					<b>");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("</b>님의 방문을 환영합니다. <br>\r\n");
                  out.write("					<br>\r\n");
                  out.write("					<div align=\"center\">\r\n");
                  out.write("						<a href=\"");
                  out.print(contextPath);
                  out.write("/myPage.me\">마이페이지</a> <a\r\n");
                  out.write("							href=\"");
                  out.print(contextPath);
                  out.write("/logout.me\">로그아웃</a>\r\n");
                  out.write("					</div>\r\n");
                  out.write("				</div>\r\n");
                  out.write("			");
                  int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
              _jspx_th_c_005fotherwise_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
            }
            out.write("\r\n");
            out.write("		");
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        _jspx_th_c_005fchoose_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
      }
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- clear : float 스타일 속성의 영향을 받지 않도록 처리 / both: 왼쪽 오른쪽 둘 다 영향 받지 않도록-->\r\n");
      out.write("	<br clear=\"both\">\r\n");
      out.write("	<br>\r\n");
      out.write("	<div class=\"nav-area\" align=\"center\">\r\n");
      out.write("		<div class=\"menu\">\r\n");
      out.write("			<a href=\"");
      out.print(contextPath);
      out.write("\">Home</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"menu\">\r\n");
      out.write("			<a href=\"");
      out.print(contextPath);
      out.write("/list.no\">공지사항</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"menu\">\r\n");
      out.write("			<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?cpage=1\">일반게시판</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"menu\">\r\n");
      out.write("			<a href=\"\">사진게시판</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	<div>\r\n");
      out.write("		<br>\r\n");
      out.write("		<h2 align=\"center\">마이페이지</h2>\r\n");
      out.write("		<form action=\"");
      out.print(contextPath);
      out.write("/update.me\" id=\"enroll-form\"\r\n");
      out.write("			method=\"post\">\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>* 아이디</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"userId\" maxlength=\"12\"\r\n");
      out.write("						value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>* 이름</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"userName\" maxlength=\"6\"\r\n");
      out.write("						value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>전화번호</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"phone\" placeholder=\"- 포함해서 입력\"\r\n");
      out.write("						value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.phone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>이메일</td>\r\n");
      out.write("					<td><input type=\"email\" name=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>주소</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"address\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.address }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>관심분야</td>\r\n");
      out.write("					<td colspan=\"2\"><input type=\"checkbox\" name=\"interest\"\r\n");
      out.write("						id=\"sports\" value=\"운동\"> <label for=\"sports\">운동</label> <input\r\n");
      out.write("						type=\"checkbox\" name=\"interest\" id=\"climbing\" value=\"등산\">\r\n");
      out.write("						<label for=\"climbing\">등산</label> <input type=\"checkbox\"\r\n");
      out.write("						name=\"interest\" id=\"fishing\" value=\"낚시\"> <label\r\n");
      out.write("						for=\"fishing\">낚시</label> <br> <input type=\"checkbox\"\r\n");
      out.write("						name=\"interest\" id=\"cooking\" value=\"요리\"> <label\r\n");
      out.write("						for=\"cooking\">요리</label> <input type=\"checkbox\" name=\"interest\"\r\n");
      out.write("						id=\"game\" value=\"게임\"> <label for=\"game\">게임</label> <input\r\n");
      out.write("						type=\"checkbox\" name=\"interest\" id=\"movie\" value=\"영화\"> <label\r\n");
      out.write("						for=\"movie\">영화</label></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("			<script>\r\n");
      out.write("            	const interest = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.interest}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"; // \"운동, 요리\", 유저 정보에 포함된 데이터\r\n");
      out.write("            	// input 태그의 name 속성이 interest인 요소 배열\r\n");
      out.write("            	const interestInput = document.querySelectorAll(\"input[name=interest]\");\r\n");
      out.write("            	\r\n");
      out.write("           		for (let input of interestInput) {\r\n");
      out.write("           			// 문자열A.includes(문자열B) => 문자열A에 문자열B가 포함되어 있는지 여부\r\n");
      out.write("           			if(interest.includes(input.value)) {	// 유저 정보에 포함된 데이터에 해당 input요소의 value값이 포함되어 있다면\r\n");
      out.write("           				input.checked = true;	// 해당 input요소(checkbox)를 체크된 상태로 변경\r\n");
      out.write("           			}\r\n");
      out.write("           		}\r\n");
      out.write("            </script>\r\n");
      out.write("\r\n");
      out.write("			<br> <br>\r\n");
      out.write("\r\n");
      out.write("			<div align=\"center\">\r\n");
      out.write("				<button type=\"submit\" class=\"btn btn-primary\">정보변경</button>\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-warning\" data-bs-toggle=\"modal\"\r\n");
      out.write("					data-bs-target=\"#changePwdModal\">비밀번호변경</button>\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-danger\" data-bs-toggle=\"modal\"\r\n");
      out.write("					data-bs-target=\"#deleteMemberModal\">회원탈퇴</button>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<br> <br>\r\n");
      out.write("		</form>\r\n");
      out.write("		<!--  비밀번호 변경용 모달 -->\r\n");
      out.write("		<div align=\"center\" class=\"modal fade\" id=\"changePwdModal\">\r\n");
      out.write("			<div class=\"modal-dialog\">\r\n");
      out.write("				<div class=\"modal-content\">\r\n");
      out.write("					<!-- 모달의 헤더 부분 -->\r\n");
      out.write("					<div  class=\"modal-header\">\r\n");
      out.write("						<h1 class=\"modal-title fs-5\" align=\"center\">비밀번호 변경</h1>\r\n");
      out.write("						<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("							aria-label=\"Close\"></button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!--  모달 바디 부분 -->\r\n");
      out.write("					<div class=\"modal-body\">\r\n");
      out.write("						<form action=\"");
      out.print( contextPath );
      out.write("/updatePwd.me\" method=\"post\">\r\n");
      out.write("							<!-- 아이디 정보 type='hidden' -->\r\n");
      out.write("							<input type=\"hidden\" name=\"userId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("							<!-- 입력받을 데이터: 현재 비밀번호/변경할 비밀번호/변경할 비밀번호 확인 -->\r\n");
      out.write("							<table>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>현재 비밀번호</td>\r\n");
      out.write("									<td><input type=\"password\" name=\"userPwd\" required /></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>변경할 비밀번호</td>\r\n");
      out.write("									<td><input type=\"password\" name=\"updatePwd\" required /></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>변경할 비밀번호 확인</td>\r\n");
      out.write("									<td><input type=\"password\" name=\"updatePwdCheck\" required />\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</table>\r\n");
      out.write("							<br>\r\n");
      out.write("							<button type=\"submit\" id=\"edit-pwd-btn\" class=\"btn btn-sm btn-warning\">비밀번호 변경</button>\r\n");
      out.write("						</form>\r\n");
      out.write("						<!-- 변경할 비밀번호와 변경할 비밀번호 확인 값이 동일한지 체크 -->\r\n");
      out.write("						<script>\r\n");
      out.write("							document.getElementById(\"edit-pwd-btn\").onclick = function() {\r\n");
      out.write("								if ($(\"input[name=updatePwd]\").val() !==\r\n");
      out.write("										$(\"input[name=updatePwdCheck]\").val()) {\r\n");
      out.write("									alert(\"입력한 비밀번호의 값이 다릅니다.\");\r\n");
      out.write("									return false;		// 기존 이벤트를 동작하지 않도록 하기 위해 false를 리턴\r\n");
      out.write("								}\r\n");
      out.write("							}\r\n");
      out.write("						</script>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--  --------------- -->\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<!--  회원탈퇴용 모달 -->\r\n");
      out.write("		<div align=\"center\" class=\"modal fade\" id=\"deleteMemberModal\">\r\n");
      out.write("			<div class=\"modal-dialog\">\r\n");
      out.write("				<div class=\"modal-content\">\r\n");
      out.write("					<!-- 모달의 헤더 부분 -->\r\n");
      out.write("					<div  class=\"modal-header\">\r\n");
      out.write("						<h1 class=\"modal-title fs-5\" align=\"center\">회원 탈퇴</h1>\r\n");
      out.write("						<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("							aria-label=\"Close\"></button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!--  모달 바디 부분 -->\r\n");
      out.write("					<div class=\"modal-body\">\r\n");
      out.write("						<form action=\"");
      out.print( contextPath );
      out.write("/delete.me\" method=\"post\">\r\n");
      out.write("							<!-- 입력받을 데이터: 현재 비밀번호/변경할 비밀번호/변경할 비밀번호 확인 -->\r\n");
      out.write("							<b>탈퇴 후 복구가 불가능합니다.<br>\r\n");
      out.write("							   정말로 탈퇴하시겠습니까 ?\r\n");
      out.write("							</b>\r\n");
      out.write("							<br><br>\r\n");
      out.write("							<input type=\"hidden\" name=\"userId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("							비밀번호 : <input type=\"password\" name=\"userPwd\" />\r\n");
      out.write("							<br><br><br>\r\n");
      out.write("							");
      out.write("\r\n");
      out.write("							<button type=\"submit\" id=\"edit-pwd-btn\" class=\"btn btn-danger\">회원 탈퇴</button>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--  --------------- -->\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /views/member/../common/menubar.jsp(65,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alertMsg != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		<script>\r\n");
          out.write("			alert(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alertMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\")\r\n");
          out.write("		</script>\r\n");
          out.write("		");
          if (_jspx_meth_c_005fremove_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    boolean _jspx_th_c_005fremove_005f0_reused = false;
    try {
      _jspx_th_c_005fremove_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fremove_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /views/member/../common/menubar.jsp(69,2) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setVar("alertMsg");
      // /views/member/../common/menubar.jsp(69,2) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setScope("session");
      int _jspx_eval_c_005fremove_005f0 = _jspx_th_c_005fremove_005f0.doStartTag();
      if (_jspx_th_c_005fremove_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.reuse(_jspx_th_c_005fremove_005f0);
      _jspx_th_c_005fremove_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fremove_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fremove_005f0_reused);
    }
    return false;
  }
}
